### ISSUE TITLE
`Feature`: Build/Version-Number in the GUI

### ISSUE THREAD

**Issue by Shirkanesi** [kit-sdq/programming-lecture-eclipse-artemis#190]
**Describe the solution you'd like**
When the student-edition gets used we might get some (a lot of?) bug-reports or feature requests.
It would be quite convenient to display a build/version number somewhere so it'll be clear for everyone in which version the issue was encountered (hence there will always be someone who forgets to update their software).

Maybe we'll find a way to bundle the name of the tag of the release somewhere into the finished product.

**Comment by Shirkanesi** [comment]
We could use something like this in the products-workflow to echo the current tag into a specific file (before the mvn-build). 
Then the plugin could just load the contents of this file on startup and display it in the settings or something like that.

```yaml
    - name: Dump Tag-Name
      run: echo ${{ github.ref }} | sed "s/refs\/tags\///" > test.txt
      if: startsWith(github.ref, 'refs/tags/v')
```
